### ISSUE TITLE
picStuff.py missing images to resize

### ISSUE THREAD

**Issue by kirtanechiron** [rkjones4/GANGogh#4]
This project is amazing. I’m trying to run the code though and picStuff.py keeping saying “missed it”. It creates the right folders but doesn’t seem to be resizing the pictures. Any ideas on how to solve this problem?

**Comment by rkjones4** [comment]
Can you edit the code to print the error message you are getting instead of missed it: and then post it here? could be that imread changed

**Comment by kirtanechiron** [comment]
It does this for every image from the fullimages folder scrapped from WikiArt:
0fullimages/genre-painting\anders-zorn+in-my-gondola-1894.jpg
missed it: fullimages/genre-painting\anders-zorn+in-my-gondola-1894.jpg

**Comment by kirtanechiron** [comment]
Alright, so I changed line 27 of picStuff.py from 
```
source = style + '\\' + f
```
to
```
source = style + '/' + f
```
Now it's resizing the pictures correctly, however it's putting them in a folder called "smallimagesfullimages" and I think it's supposed to just put it in a folder called "small images" right?
Also, the images are being named like this: figurative\105.png. Is that what we want?

**Comment by rkjones4** [comment]
Oh are you running this on a mac? This code is set up to run on windows. In the file processing stuff you might need to change some of the logic, but in the end ideally the folder is called smallimages and there are sub-folders within it i.e. figurative and then the ##.png go inside the sub-folders

smallimages
  --figurative
     - 1.png
     - 2.png
  --landscape
     - 1.png
     - 2.png

etc

**Comment by kirtanechiron** [comment]
I'm running this on a VM (linux debian-9-stretch). As long as the images are organized in the structure you described though, the GANgogh.py model should be able to work with them right?

**Comment by rkjones4** [comment]
You'll definitely need to change some code in tflib/wikiartGenre (i.e. the path, maybe more), and maybe some code in ganGogh.py that saves the images but otherwise I think it should work, if you run into any errors paste them here and I'll try to help!
